/*
	OTA_FltSaveOrderSudzc.m
	Creates a list of the services available with the OTA_FltSaveOrder prefix.
	Generated by SudzC.com
*/
#import "OTA_FltSaveOrderSudzc.h"

@implementation OTA_FltSaveOrderSudzC

@synthesize logging, server, defaultServer;

@synthesize oTA_FltSaveOrder;


#pragma mark Initialization

-(id)initWithServer:(NSString*)serverName{
	if(self = [self init]) {
		self.server = serverName;
	}
	return self;
}

+(OTA_FltSaveOrderSudzC*)sudzc{
	return (OTA_FltSaveOrderSudzC*)[[[OTA_FltSaveOrderSudzC alloc] init] autorelease];
}

+(OTA_FltSaveOrderSudzC*)sudzcWithServer:(NSString*)serverName{
	return (OTA_FltSaveOrderSudzC*)[[[OTA_FltSaveOrderSudzC alloc] initWithServer:serverName] autorelease];
}

#pragma mark Methods

-(void)setLogging:(BOOL)value{
	logging = value;
	[self updateServices];
}

-(void)setServer:(NSString*)value{
	[server release];
	server = [value retain];
	[self updateServices];
}

-(void)updateServices{

	[self updateService: self.oTA_FltSaveOrder];
}

-(void)updateService:(SoapService*)service{
	service.logging = self.logging;
	if(self.server == nil || self.server.length < 1) { return; }
	service.serviceUrl = [service.serviceUrl stringByReplacingOccurrencesOfString:defaultServer withString:self.server];
}

#pragma mark Getter Overrides


-(OTA_FltSaveOrderOTA_FltSaveOrder*)oTA_FltSaveOrder{
	if(oTA_FltSaveOrder == nil) {
		oTA_FltSaveOrder = [[OTA_FltSaveOrderOTA_FltSaveOrder alloc] init];
	}
	return oTA_FltSaveOrder;
}


@end
			