/*
	OTA_HotelResOTA_HotelRes.m
	The implementation classes and methods for the OTA_HotelRes web service.
	Generated by SudzC.com
*/

#import "OTA_HotelResOTA_HotelRes.h"
				
#import "Soap.h"
	

/* Implementation of the service */
				
@implementation OTA_HotelResOTA_HotelRes

	- (id) init
	{
		if(self = [super init])
		{
			self.serviceUrl = @"http://openapi.ctrip.com/Hotel/OTA_HotelRes.asmx";
			self.namespace = @"http://ctrip.com/";
			self.headers = nil;
			self.logging = NO;
		}
		return self;
	}
	
	- (id) initWithUsername: (NSString*) username andPassword: (NSString*) password {
		if(self = [super initWithUsername:username andPassword:password]) {
		}
		return self;
	}
	
	+ (OTA_HotelResOTA_HotelRes*) service {
		return [OTA_HotelResOTA_HotelRes serviceWithUsername:nil andPassword:nil];
	}
	
	+ (OTA_HotelResOTA_HotelRes*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password {
		return [[[OTA_HotelResOTA_HotelRes alloc] initWithUsername:username andPassword:password] autorelease];
	}

		
	// Returns NSString*
	/*  */
	- (SoapRequest*) Request: (id <SoapDelegate>) handler requestXML: (NSString*) requestXML
	{
		return [self Request: handler action: nil requestXML: requestXML];
	}

	- (SoapRequest*) Request: (id) _target action: (SEL) _action requestXML: (NSString*) requestXML
		{
		NSMutableArray* _params = [NSMutableArray array];
		
		[_params addObject: [[[SoapParameter alloc] initWithValue: requestXML forName: @"requestXML"] autorelease]];
		NSString* _envelope = [Soap createEnvelope: @"Request" forNamespace: self.namespace withParameters: _params withHeaders: self.headers];
		SoapRequest* _request = [SoapRequest create: _target action: _action service: self soapAction: @"http://ctrip.com/Request" postData: _envelope deserializeTo: @"NSString"];
		[_request send];
		return _request;
	}


@end
	