/*
	OTA_HotelResOTA_HotelRes.h
	The interface definition of classes and methods for the OTA_HotelRes web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				

/* Interface for the service */
				
@interface OTA_HotelResOTA_HotelRes : SoapService
		
	// Returns NSString*
	/*  */
	- (SoapRequest*) Request: (id <SoapDelegate>) handler requestXML: (NSString*) requestXML;
	- (SoapRequest*) Request: (id) target action: (SEL) action requestXML: (NSString*) requestXML;

		
	+ (OTA_HotelResOTA_HotelRes*) service;
	+ (OTA_HotelResOTA_HotelRes*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	