/*
	OTA_HotelResSudzc.m
	Creates a list of the services available with the OTA_HotelRes prefix.
	Generated by SudzC.com
*/
#import "OTA_HotelResSudzc.h"

@implementation OTA_HotelResSudzC

@synthesize logging, server, defaultServer;

@synthesize oTA_HotelRes;


#pragma mark Initialization

-(id)initWithServer:(NSString*)serverName{
	if(self = [self init]) {
		self.server = serverName;
	}
	return self;
}

+(OTA_HotelResSudzC*)sudzc{
	return (OTA_HotelResSudzC*)[[[OTA_HotelResSudzC alloc] init] autorelease];
}

+(OTA_HotelResSudzC*)sudzcWithServer:(NSString*)serverName{
	return (OTA_HotelResSudzC*)[[[OTA_HotelResSudzC alloc] initWithServer:serverName] autorelease];
}

#pragma mark Methods

-(void)setLogging:(BOOL)value{
	logging = value;
	[self updateServices];
}

-(void)setServer:(NSString*)value{
	[server release];
	server = [value retain];
	[self updateServices];
}

-(void)updateServices{

	[self updateService: self.oTA_HotelRes];
}

-(void)updateService:(SoapService*)service{
	service.logging = self.logging;
	if(self.server == nil || self.server.length < 1) { return; }
	service.serviceUrl = [service.serviceUrl stringByReplacingOccurrencesOfString:defaultServer withString:self.server];
}

#pragma mark Getter Overrides


-(OTA_HotelResOTA_HotelRes*)oTA_HotelRes{
	if(oTA_HotelRes == nil) {
		oTA_HotelRes = [[OTA_HotelResOTA_HotelRes alloc] init];
	}
	return oTA_HotelRes;
}


@end
			