/*
	OTA_HotelResSudzc.h
	Creates a list of the services available with the OTA_HotelRes prefix.
	Generated by SudzC.com
*/
#import "OTA_HotelResOTA_HotelRes.h"

@interface OTA_HotelResSudzC : NSObject {
	BOOL logging;
	NSString* server;
	NSString* defaultServer;
OTA_HotelResOTA_HotelRes* oTA_HotelRes;

}

-(id)initWithServer:(NSString*)serverName;
-(void)updateService:(SoapService*)service;
-(void)updateServices;
+(OTA_HotelResSudzC*)sudzc;
+(OTA_HotelResSudzC*)sudzcWithServer:(NSString*)serverName;

@property (nonatomic) BOOL logging;
@property (nonatomic, retain) NSString* server;
@property (nonatomic, retain) NSString* defaultServer;

@property (nonatomic, retain, readonly) OTA_HotelResOTA_HotelRes* oTA_HotelRes;

@end
			