/*
	OTA_FltSaveOrderOTA_FltSaveOrder.h
	The interface definition of classes and methods for the OTA_FltSaveOrder web service.
	Generated by SudzC.com
*/
				
#import "Soap.h"
	
/* Add class references */
				

/* Interface for the service */
				
@interface OTA_FltSaveOrderOTA_FltSaveOrder : SoapService
		
	// Returns NSString*
	/*  */
	- (SoapRequest*) Request: (id <SoapDelegate>) handler requestXML: (NSString*) requestXML;
	- (SoapRequest*) Request: (id) target action: (SEL) action requestXML: (NSString*) requestXML;

		
	+ (OTA_FltSaveOrderOTA_FltSaveOrder*) service;
	+ (OTA_FltSaveOrderOTA_FltSaveOrder*) serviceWithUsername: (NSString*) username andPassword: (NSString*) password;
@end
	