/*
 Soap+Prefix.m
 Provides Soap methods with access to the custom prefix.
 Generated by SudzC.com
*/

#import "Soap.h"
#import "Soap+Prefix.h"

@implementation Soap (Prefix)

+(NSString*)prefix { return @"OTA_HotelSearch"; }

@end
			